name: lint-nuxt-app
run-name: ${{ github.actor }} is linting the Nuxt application
on: [pull_request]
jobs:
  Lint-Nuxt-App:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd nuxt-app
      - run: npm ci
      - run: npm run lint
